mysql:
  host: 127.0.0.1
  port: 3306
  db: hblog_db
  user: root
  password: "123456"
  log_level: dev
  config: charset=utf8mb4&parseTime=True&loc=Local
logger:
  level: info
  director: log
  show_line: true
  log_in_console: true
  prefix: '[hjf_blog]'
site_info:
  created_at: "2025-04-14"
  bei_an: 闽ICP备2025095031号
  title: 雾念的知识空间
  qq_image: /uploads/file/admin/wallhaven-zy1ooy_1280x1024_20250414212739.png
  version: 1.0.0
  email: eogod124@gmail.com
  wechat_image: /uploads/file/admin/img5_20250414212747.jpg
  name: 雾念
  job: 学生啦
  addr: 福建宁德
  slogan: 雾念的知识空间
  slogan_en: WuNianBLOG
  web: ""
  bilibili_url: https://space.bilibili.com/457254347
  gitee_url: https://gitee.com/eo_wunian
  github_url: https://github.com/Wunian3
system:
  host: 0.0.0.0
  port: 8080
  env: release
qq:
  app_id: 需要修改
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: false
  access_key: w0_GVYiOBUeSpg4pGbsHGBTa9geB1WWJqUXzjj2z
  secret_key: ogktTWTpumr2h5oUbRGbiz2EPjZ9ltqYlr4psOpm
  bucket: wunianblog
  cdn: su2l8211x.hn-bkt.clouddn.com/
  zone: z2
  prefix: wunianblog
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: hwunian@qq.com
  password: tiabzlvumcjrhjeg
  default_from_email: gerneboke
  use_ssl: false
  user_tls: false
jwt:
  secret: hjf
  expires: 48
  issuer: "1234"
upload:
  size: 6
  path: uploads/file
redis:
  ip: 127.0.0.1
  port: 6379
  password: redis
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  isAnonymous: false
  isShowTime: false
  defaultLimit: 50
  contentLength: 10000
  welcomeTitle: 雾念的学习室
  isOnlinePeople: true
  isSendImage: true
  isSendFile: false
  isMd: true
gaode:
  enable: true
  key: 2ea0778aa0b96da0ce2abfc45fe22ca0
big-model:
  setting:
    name: qwen
    enable: true
    api-key: "sk-f163b622cce7400bb29f63fbc2f7cab9"
    api-secret: ""
    title: "雾念的千问频道"
    prompt: ""
  model-list:
  - label: 通义千问
    value: qwen
    disable: false
  - label: 文心一言
    value: wenxin
    disable: true
  - label: 星火大模型
    value: xinghuo
    disable: true
  - label: 天工大模型
    value: tiangong
    disable: true
  - label: DeepSeek
    value: deepseek
    disable: true
  session-setting:
    chat-scope: 21
    session-scope: 21
    day-scope: 100
