mysql:
  host:127.0.0.1
  port:3306
  db:hjf_blog
  user:root
  password:root
  log_level:dev
logger:
  level:info
  director:log
  show-line:true
  log-in-console:true
  prefix:'[hjf_blog]'
system:
  host:"0.0.0.0"
  port:8080
  env:dev
